project:
  type: book

book:
  title: "test double number"
  author: "Norah Jones"
  date: "10/05/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

# number-sections: false

format:
  pdf:
    pdf-engine: weasyprint
